dbVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: workshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: mongo:latest
        imagePullPolicy: Always
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongo-sec
                key: username
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongo-sec
                key: password
        ports:
        - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  namespace: workshop
  name: db-svc
spec:
  selector:
    app: db
  ports:
  - name: db-svc
    protocol: TCP
    port: 27017
    targetPort: 27017
    nodePort: 30007
  type: NodePort
